### ISSUE TITLE
Bot/Front: Учредители - юридические лица

### ISSUE THREAD

**Issue by osintsev** [SuperbCoders/F-telegram-bot-RKO#10]
Вижу страницу https://rko-bot.spaaace.io/founders

1. поправить стиль заголовка
2. поле «доля...» сделать короче, там максимум 3 символа может быть (100%)

**Важно:** Форма должна выводиться, если клиент не является индивидуальным предпринимателем (ОПФ клиента не равна “Индивидуальный предприниматель” или ОКОПФ клиента не равен “50102”)

**Comment by L4legenda** [comment]
Откуда взять информацию об ОПФ или ОКОПФ ?

**Comment by osintsev** [comment]
Понятия не имею( Может дадата отдает тип компании? Короче для ИП не показываем ряд полей. Полагаю, что по дадате можно понять, если выбранная компания является ИП
