### ISSUE TITLE
Front: согласие на рассылку

### ISSUE THREAD

**Issue by osintsev** [SuperbCoders/F-telegram-bot-RKO#27]
На экране выбора тарифа, после доп услуг добавить согласие на смс рассылку

1. Добавить блок «Согласие на получение информационной рассылки» с переключателем да/нет. 
2. Разместить на форме следующий текст: “Заявитель дает согласие на получение им предложений, информации о продуктах/ услугах, рекламы и иной информации от Банка, Партнеров Банка по почте, по сетям электросвязи, в том числе путем контактов по телефону, электронной почте, с помощью СМС - сообщений и иными способами.”  
3. Переключатель должен быть установлен в положение “Да”. Клиент может выбрать значение “Нет”. 
<img width="569" alt="Screenshot 2022-12-21 at 11 25 34" src="https://user-images.githubusercontent.com/5693096/208894420-ad49bc74-8d1a-454f-babf-2ea9a4ae6474.png">

**Comment by L4legenda** [comment]
Какой должен быть дизайн у этого экрана ?
Сейчас реализован так 
https://rko-bot.spaaace.io/consent_receive_newsletter

**Comment by osintsev** [comment]
Дорисуем, дадим. Сегодня-завтра. Пока пусть будет так как по твоей ссылке, главное, чтобы работало
