### ISSUE TITLE
Bot/Front: Dadata для адресов подключена криво

### ISSUE THREAD

**Issue by osintsev** [SuperbCoders/F-telegram-bot-RKO#3]
Для всех полей с адресами сейчас подключена dadata (сервис выбор адреса из справочника). Но работает криво! Невозможно с подсказкой вбить точный адрес до дома.

Скорее всего дело в конфигурации dadata, вот тут пример реализации правильный
https://feijoa-develop.moos.solutions/credits/start/ – на втором шаге формы есть адрес прописки
Надо заполнить первую форму произвольно, в окне смс вбить 000000 и будет доступ на второй шаг. Посмотреть js дадаты.

Подключить такой выбор точного адреса ВСЕМ полям с адресом на любом шаге анкеты.

**Comment by L4legenda** [comment]
Тут дело не в dadata а в компоненте который ее выводит, он взят из vuetify. Он дополнительно фильтрует поля, из-за чего она ничего не выводит. Тут вижу только решение написать свой компонент вывода.

**Comment by osintsev** [comment]
ok
