### ISSUE TITLE
Bot/Front: порядок шагов

### ISSUE THREAD

**Issue by osintsev** [SuperbCoders/F-telegram-bot-RKO#30]
1. Выбор компании
2. Контакты
3. Адреса
4. Физлица
5. Документы
6. Структура органов управления
7. Учредители юр лица
8. Выгодоприобретатели
9. Персонал
10. Виды договоров
11. Сведения FatCA
12. Кодовое слово
13. Тарифы + доп услуги
14. Подтверждение + условия сервиса
15. Успех

Вроде ничего не забыл

**Comment by L4legenda** [comment]
Что значит + ?
Это окно должно как-то появляться на экране слева.
То есть доп услуги должны как-то появляться у Тарифов ?

**Comment by osintsev** [comment]
+ значит на одном экране, смотри другие тикеты, там все описано

**Comment by Ekd0111** [comment]
Ориентируемся на порядок экранов в файле СкриншотыЗаполнитьАнкету
