### ISSUE TITLE
Bot/Front: Шаг «Сведения о физических лицах организации»

### ISSUE THREAD

**Issue by osintsev** [SuperbCoders/F-telegram-bot-RKO#8]
После шага «Адреса» идет шаг с информацией о физлицах. 
Тут много всего. 

А. Физлиц может быть несколько, поэтому нужно уметь добавлять/удалять 
Б. Поля и их описания. 
Надо сверить с текущей версткой. Если есть лишние, то удалить, если что-то меняется относительно текущей версии, то поменять. 

1. «Роль лица»: обязательное, чек-бокс 
Значения: [x] Акционер/учредитель  [x]  ЕИО  [x]  Бенифициар 
2. «Доля»: выводить, если выбрано “Акционер/учредитель”, обязательное 
3. «Должность»: выводить, если выбрано “ЕИО”, обязательное
4. «Фамилия» обязательное
5. «Имя» обязательное 
6. «Отчество»: обязательное
7. «ИНН»: обязательное, только цифры 12 штук (перепроверить длину)
8. «Телефон»: обязательное, маска
9. «Эл. почта»: обязательное, маска
10.  «Пол»: обязательное, радио 
Значения:  - Мужской       - Женский
11. «Гражданство»: обязательное, справочник стран, в котором первым значением должна стоять “Россия” 
Справочник взять в dadata (наверное)
12.  «Дата рождения»: обязательное. не календарь, а маска дд.мм.гггг
13. «Место рождения»: обязательное (просто текстовое поле, не справочник)
14.   «Тип документа, удостоверяющего личность» : обязательное  , селект
Значения:       
– Паспорт гражданина Российской Федерации (Код 21)
– Дипломатический паспорт, служебный паспорт, удостоверяющие личность гражданина РФ за пределами РФ (Код 22)
– Временное удостоверение личности гражданина РФ, выдаваемое на период оформления паспорта гражданина РФ (Код 26)
– Свидетельство о рождении гражданина РФ (для граждан РФ в возрасте до 14 лет) (Код 27)
– Иные документы, признаваемые документами, удостоверяющими личность гражданина РФ в соответствии с законодательством РФ (Код 28)
ЭТОТ СПРАВОЧНИК ПРЕДЛАГАЮ ЗАХАРДКОДИТЬ НА ФРОНТЕ. ЧТО ПЕРЕДАВАТЬ В JSON/Back УТОЧНИТЬ У КЛИЕНТА!
15. «Серия»: обязательное 
16. «Номер»: обязательное  
17. «Дата выдачи»: обязательное  дд.мм.гггг
18. «Кем выдан»: обязательное  - 
19. «Код подразделения » обязательное, есть для этого справочник (пример реализации тут на каком-то шаге https://feijoa-develop.moos.solutions/credits/start/)
20. «Страна проживания»: обязательное, справочник стран мира 
21. «Адрес регистрации»: обязательное, поиск адреса в dadata
22.«Адрес местонахождения совпадает с адресом регистрации»      - Да         - Нет
23. «Адрес местонахождения»: обязательное, поиск адреса в dadata. Если в предыдущем поле выбрано “Да”, то в UI не показываем, а на беке заполнить автоматически тем же значением, что в поле “Адрес регистрации”

**Comment by L4legenda** [comment]
Раньше они делились на "Наличие наблюдательного совета" и "Наличие коллегиального исполнительного органа" это удаляется и будет только одна форма ?

**Comment by osintsev** [comment]
Не понял вопрос, он к этой задаче? нужно сделать как написано в тикете.
